<?php

namespace Database\Seeders;

use App\Models\Prestasi;
use Illuminate\Database\Seeder;

class PrestasiSeeder extends Seeder
{
    public function run(): void
    {
        $dataPrestasi = [
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'KSM',
                'tingkat' => 'Nasional',
                'kategori' => 'Individu',
                'peringkat' => '1',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'KSM',
                'tingkat' => 'Nasional',
                'kategori' => 'Individu',
                'peringkat' => '2',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'KSM',
                'tingkat' => 'Nasional',
                'kategori' => 'Individu',
                'peringkat' => '3',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'OSN',
                'tingkat' => 'Nasional',
                'kategori' => 'Individu',
                'peringkat' => '1',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'OSN',
                'tingkat' => 'Nasional',
                'kategori' => 'Individu',
                'peringkat' => '2',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'OSN',
                'tingkat' => 'Nasional',
                'kategori' => 'Individu',
                'peringkat' => '3',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'O2SN',
                'tingkat' => 'Nasional',
                'kategori' => 'Individu',
                'peringkat' => '1',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'O2SN',
                'tingkat' => 'Nasional',
                'kategori' => 'Individu',
                'peringkat' => '2',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'O2SN',
                'tingkat' => 'Nasional',
                'kategori' => 'Individu',
                'peringkat' => '3',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'FLS2N',
                'tingkat' => 'Nasional',
                'kategori' => 'Individu',
                'peringkat' => '1',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'FLS2N',
                'tingkat' => 'Nasional',
                'kategori' => 'Individu',
                'peringkat' => '2',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'FLS2N',
                'tingkat' => 'Nasional',
                'kategori' => 'Individu',
                'peringkat' => '3',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'KSM',
                'tingkat' => 'Provinsi',
                'kategori' => 'Individu',
                'peringkat' => '1',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'KSM',
                'tingkat' => 'Provinsi',
                'kategori' => 'Individu',
                'peringkat' => '2',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'KSM',
                'tingkat' => 'Provinsi',
                'kategori' => 'Individu',
                'peringkat' => '3',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'OSN',
                'tingkat' => 'Provinsi',
                'kategori' => 'Individu',
                'peringkat' => '1',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'OSN',
                'tingkat' => 'Provinsi',
                'kategori' => 'Individu',
                'peringkat' => '2',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'OSN',
                'tingkat' => 'Provinsi',
                'kategori' => 'Individu',
                'peringkat' => '3',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'O2SN',
                'tingkat' => 'Provinsi',
                'kategori' => 'Individu',
                'peringkat' => '1',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'O2SN',
                'tingkat' => 'Provinsi',
                'kategori' => 'Individu',
                'peringkat' => '2',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'O2SN',
                'tingkat' => 'Provinsi',
                'kategori' => 'Individu',
                'peringkat' => '3',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'FLS2N',
                'tingkat' => 'Provinsi',
                'kategori' => 'Individu',
                'peringkat' => '1',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'FLS2N',
                'tingkat' => 'Provinsi',
                'kategori' => 'Individu',
                'peringkat' => '2',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'FLS2N',
                'tingkat' => 'Provinsi',
                'kategori' => 'Individu',
                'peringkat' => '3',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'KSM',
                'tingkat' => 'Kabupaten/Kota',
                'kategori' => 'Individu',
                'peringkat' => '1',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'KSM',
                'tingkat' => 'Kabupaten/Kota',
                'kategori' => 'Individu',
                'peringkat' => '2',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'KSM',
                'tingkat' => 'Kabupaten/Kota',
                'kategori' => 'Individu',
                'peringkat' => '3',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'OSN',
                'tingkat' => 'Kabupaten/Kota',
                'kategori' => 'Individu',
                'peringkat' => '1',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'OSN',
                'tingkat' => 'Kabupaten/Kota',
                'kategori' => 'Individu',
                'peringkat' => '2',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'OSN',
                'tingkat' => 'Kabupaten/Kota',
                'kategori' => 'Individu',
                'peringkat' => '3',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'O2SN',
                'tingkat' => 'Kabupaten/Kota',
                'kategori' => 'Individu',
                'peringkat' => '1',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'O2SN',
                'tingkat' => 'Kabupaten/Kota',
                'kategori' => 'Individu',
                'peringkat' => '2',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'O2SN',
                'tingkat' => 'Kabupaten/Kota',
                'kategori' => 'Individu',
                'peringkat' => '3',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'FLS2N',
                'tingkat' => 'Kabupaten/Kota',
                'kategori' => 'Individu',
                'peringkat' => '1',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'FLS2N',
                'tingkat' => 'Kabupaten/Kota',
                'kategori' => 'Individu',
                'peringkat' => '2',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'FLS2N',
                'tingkat' => 'Kabupaten/Kota',
                'kategori' => 'Individu',
                'peringkat' => '3',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'KSM',
                'tingkat' => 'Nasional',
                'kategori' => 'Regu/Kelompok',
                'peringkat' => '1',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'KSM',
                'tingkat' => 'Nasional',
                'kategori' => 'Regu/Kelompok',
                'peringkat' => '2',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'KSM',
                'tingkat' => 'Nasional',
                'kategori' => 'Regu/Kelompok',
                'peringkat' => '3',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'OSN',
                'tingkat' => 'Nasional',
                'kategori' => 'Regu/Kelompok',
                'peringkat' => '1',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'OSN',
                'tingkat' => 'Nasional',
                'kategori' => 'Regu/Kelompok',
                'peringkat' => '2',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'OSN',
                'tingkat' => 'Nasional',
                'kategori' => 'Regu/Kelompok',
                'peringkat' => '3',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'O2SN',
                'tingkat' => 'Nasional',
                'kategori' => 'Regu/Kelompok',
                'peringkat' => '1',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'O2SN',
                'tingkat' => 'Nasional',
                'kategori' => 'Regu/Kelompok',
                'peringkat' => '2',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'O2SN',
                'tingkat' => 'Nasional',
                'kategori' => 'Regu/Kelompok',
                'peringkat' => '3',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'FLS2N',
                'tingkat' => 'Nasional',
                'kategori' => 'Regu/Kelompok',
                'peringkat' => '1',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'FLS2N',
                'tingkat' => 'Nasional',
                'kategori' => 'Regu/Kelompok',
                'peringkat' => '2',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'FLS2N',
                'tingkat' => 'Nasional',
                'kategori' => 'Regu/Kelompok',
                'peringkat' => '3',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'KSM',
                'tingkat' => 'Provinsi',
                'kategori' => 'Regu/Kelompok',
                'peringkat' => '1',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'KSM',
                'tingkat' => 'Provinsi',
                'kategori' => 'Regu/Kelompok',
                'peringkat' => '2',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'KSM',
                'tingkat' => 'Provinsi',
                'kategori' => 'Regu/Kelompok',
                'peringkat' => '3',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'OSN',
                'tingkat' => 'Provinsi',
                'kategori' => 'Regu/Kelompok',
                'peringkat' => '1',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'OSN',
                'tingkat' => 'Provinsi',
                'kategori' => 'Regu/Kelompok',
                'peringkat' => '2',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'OSN',
                'tingkat' => 'Provinsi',
                'kategori' => 'Regu/Kelompok',
                'peringkat' => '3',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'O2SN',
                'tingkat' => 'Provinsi',
                'kategori' => 'Regu/Kelompok',
                'peringkat' => '1',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'O2SN',
                'tingkat' => 'Provinsi',
                'kategori' => 'Regu/Kelompok',
                'peringkat' => '2',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'O2SN',
                'tingkat' => 'Provinsi',
                'kategori' => 'Regu/Kelompok',
                'peringkat' => '3',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'FLS2N',
                'tingkat' => 'Provinsi',
                'kategori' => 'Regu/Kelompok',
                'peringkat' => '1',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'FLS2N',
                'tingkat' => 'Provinsi',
                'kategori' => 'Regu/Kelompok',
                'peringkat' => '2',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'FLS2N',
                'tingkat' => 'Provinsi',
                'kategori' => 'Regu/Kelompok',
                'peringkat' => '3',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'KSM',
                'tingkat' => 'Kabupaten/Kota',
                'kategori' => 'Regu/Kelompok',
                'peringkat' => '1',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'KSM',
                'tingkat' => 'Kabupaten/Kota',
                'kategori' => 'Regu/Kelompok',
                'peringkat' => '2',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'KSM',
                'tingkat' => 'Kabupaten/Kota',
                'kategori' => 'Regu/Kelompok',
                'peringkat' => '3',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'OSN',
                'tingkat' => 'Kabupaten/Kota',
                'kategori' => 'Regu/Kelompok',
                'peringkat' => '1',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'OSN',
                'tingkat' => 'Kabupaten/Kota',
                'kategori' => 'Regu/Kelompok',
                'peringkat' => '2',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'OSN',
                'tingkat' => 'Kabupaten/Kota',
                'kategori' => 'Regu/Kelompok',
                'peringkat' => '3',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'O2SN',
                'tingkat' => 'Kabupaten/Kota',
                'kategori' => 'Regu/Kelompok',
                'peringkat' => '1',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'O2SN',
                'tingkat' => 'Kabupaten/Kota',
                'kategori' => 'Regu/Kelompok',
                'peringkat' => '2',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'O2SN',
                'tingkat' => 'Kabupaten/Kota',
                'kategori' => 'Regu/Kelompok',
                'peringkat' => '3',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'FLS2N',
                'tingkat' => 'Kabupaten/Kota',
                'kategori' => 'Regu/Kelompok',
                'peringkat' => '1',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'FLS2N',
                'tingkat' => 'Kabupaten/Kota',
                'kategori' => 'Regu/Kelompok',
                'peringkat' => '2',
            ],
            [
                'jenis' => 'Olimpiade/Kejuaraan',
                'nama' => 'FLS2N',
                'tingkat' => 'Kabupaten/Kota',
                'kategori' => 'Regu/Kelompok',
                'peringkat' => '3',
            ],
            [
                'jenis' => 'Hafalan Al-Quran',
                'nama' => 'Hafalan Al-Quran 1 Juz',
            ],
            [
                'jenis' => 'Hafalan Al-Quran',
                'nama' => 'Hafalan Al-Quran 2 Juz',
            ],
            [
                'jenis' => 'Hafalan Al-Quran',
                'nama' => 'Hafalan Al-Quran 3 Juz',
            ],
            [
                'jenis' => 'Hafalan Al-Quran',
                'nama' => 'Hafalan Al-Quran 4 Juz',
            ],
            [
                'jenis' => 'Hafalan Al-Quran',
                'nama' => 'Hafalan Al-Quran 5 Juz',
            ],
            [
                'jenis' => 'Hafalan Al-Quran',
                'nama' => 'Hafalan Al-Quran 7 Juz',
            ],
            [
                'jenis' => 'Hafalan Al-Quran',
                'nama' => 'Hafalan Al-Quran 8 Juz',
            ],
            [
                'jenis' => 'Hafalan Al-Quran',
                'nama' => 'Hafalan Al-Quran 9 Juz',
            ],
            [
                'jenis' => 'Hafalan Al-Quran',
                'nama' => 'Hafalan Al-Quran 10 Juz',
            ],
            [
                'jenis' => 'Hafalan Al-Quran',
                'nama' => 'Hafalan Al-Quran 11 Juz',
            ],
            [
                'jenis' => 'Hafalan Al-Quran',
                'nama' => 'Hafalan Al-Quran 12 Juz',
            ],
            [
                'jenis' => 'Hafalan Al-Quran',
                'nama' => 'Hafalan Al-Quran 13 Juz',
            ],
            [
                'jenis' => 'Hafalan Al-Quran',
                'nama' => 'Hafalan Al-Quran 14 Juz',
            ],
            [
                'jenis' => 'Hafalan Al-Quran',
                'nama' => 'Hafalan Al-Quran 15 Juz',
            ],
            [
                'jenis' => 'Hafalan Al-Quran',
                'nama' => 'Hafalan Al-Quran 16 Juz',
            ],
            [
                'jenis' => 'Hafalan Al-Quran',
                'nama' => 'Hafalan Al-Quran 17 Juz',
            ],
            [
                'jenis' => 'Hafalan Al-Quran',
                'nama' => 'Hafalan Al-Quran 18 Juz',
            ],
            [
                'jenis' => 'Hafalan Al-Quran',
                'nama' => 'Hafalan Al-Quran 19 Juz',
            ],
            [
                'jenis' => 'Hafalan Al-Quran',
                'nama' => 'Hafalan Al-Quran 20 Juz',
            ],
            [
                'jenis' => 'Hafalan Al-Quran',
                'nama' => 'Hafalan Al-Quran 21 Juz',
            ],
            [
                'jenis' => 'Hafalan Al-Quran',
                'nama' => 'Hafalan Al-Quran 22 Juz',
            ],
            [
                'jenis' => 'Hafalan Al-Quran',
                'nama' => 'Hafalan Al-Quran 23 Juz',
            ],
            [
                'jenis' => 'Hafalan Al-Quran',
                'nama' => 'Hafalan Al-Quran 24 Juz',
            ],
            [
                'jenis' => 'Hafalan Al-Quran',
                'nama' => 'Hafalan Al-Quran 25 Juz',
            ],
            [
                'jenis' => 'Hafalan Al-Quran',
                'nama' => 'Hafalan Al-Quran 26 Juz',
            ],
            [
                'jenis' => 'Hafalan Al-Quran',
                'nama' => 'Hafalan Al-Quran 27 Juz',
            ],
            [
                'jenis' => 'Hafalan Al-Quran',
                'nama' => 'Hafalan Al-Quran 28 Juz',
            ],
            [
                'jenis' => 'Hafalan Al-Quran',
                'nama' => 'Hafalan Al-Quran 29 Juz',
            ],
            [
                'jenis' => 'Hafalan Al-Quran',
                'nama' => 'Hafalan Al-Quran 30 Juz',
            ],
        ];

        foreach ($dataPrestasi as $data) {
            Prestasi::create($data);
        }
    }
}
