<span> {{ $record->nama }} </span>
<span> {{ $record->nik }} </span>
<span> {{ $record->nisn }} </span>
<span> {{ $record->tempat_lahir }} </span>
<span> {{ $record->tanggal_lahir }} </span>
<span> {{ $record->tahun_lulus }} </span>
<span> {{ $record->jenis_kelamin }} </span>
<span> {{ $record->golongan_darah }} </span>
<span> {{ $record->agama }} </span>
<span> {{ $record->anak_ke }} </span>
<span> {{ $record->jumlah_saudara }} </span>
<span> {{ $record->tinggal_bersama }} </span>
<span> {{ $record->jarak_ke_sekolah }} </span>
<span> {{ $record->disabilitas }} </span>
<span> {{ $record->tinggi_badan }} </span>
<span> {{ $record->berat_badan }} </span>
<span> {{ $record->no_kip }} </span>
<span> {{ $record->siswa_telepon }} </span>
<span> {{ $record->siswa_alamat }} </span>
<span> {{ $record->siswa_negara_id }} </span>
<span> {{ $record->siswa_provinsi_id }} </span>
<span> {{ $record->siswa_kabupaten_id }} </span>
<span> {{ $record->siswa_kecamatan_id }} </span>
<span> {{ $record->siswa_kelurahan_id }} </span>
<img src="{{ Storage::url($record->berkas_foto) }}" alt="Foto">
<img src="{{ Storage::url($record->berkas_kk) }}" alt="KK">
<img src="{{ Storage::url($record->berkas_akta) }}" alt="Akta">
<img src="{{ Storage::url($record->berkas_kip) }}" alt="KIP">
<img src="{{ Storage::url($record->berkas_nisn) }}" alt="NISN">
<img src="{{ Storage::url($record->berkas_skbb) }}" alt="SKBB">
<img src="{{ Storage::url($record->berkas_skab) }}" alt="SKAB">
<img src="{{ Storage::url($record->berkas_prestasi) }}" alt="Prestasi">
<span> {{ $record->ibu_nama }} </span>
<span> {{ $record->ibu_telepon }} </span>
<span> {{ $record->ibu_pekerjaan }} </span>
<span> {{ $record->ibu_status }} </span>
<span> {{ $record->ibu_alamat }} </span>
<span> {{ $record->ibu_negara_id }} </span>
<span> {{ $record->ibu_provinsi_id }} </span>
<span> {{ $record->ibu_kabupaten_id }} </span>
<span> {{ $record->ibu_kecamatan_id }} </span>
<span> {{ $record->ibu_kelurahan_id }} </span>
<span> {{ $record->ayah_nama }} </span>
<span> {{ $record->ayah_telepon }} </span>
<span> {{ $record->ayah_pekerjaan }} </span>
<span> {{ $record->ayah_status }} </span>
<span> {{ $record->ayah_alamat }} </span>
<span> {{ $record->ayah_negara_id }} </span>
<span> {{ $record->ayah_provinsi_id }} </span>
<span> {{ $record->ayah_kabupaten_id }} </span>
<span> {{ $record->ayah_kecamatan_id }} </span>
<span> {{ $record->ayah_kelurahan_id }} </span>
<span> {{ $record->wali_nama }} </span>
<span> {{ $record->wali_telepon }} </span>
<span> {{ $record->wali_pekerjaan }} </span>
<span> {{ $record->wali_status }} </span>
<span> {{ $record->wali_alamat }} </span>
<span> {{ $record->wali_negara_id }} </span>
<span> {{ $record->wali_provinsi_id }} </span>
<span> {{ $record->wali_kabupaten_id }} </span>
<span> {{ $record->wali_kecamatan_id }} </span>
<span> {{ $record->wali_kelurahan_id }} </span>
<span> {{ $record->sekolah_asal_id }} </span>
<span> {{ $record->jalur_pendaftaran_id }} </span>
<span> {{ $record->prestasi_id }} </span>
<span> {{ $record->peminatan_ekstrakurikuler }} </span>
<span> {{ $record->peminatan_pelajaran }} </span>
<span> {{ $record->nilai_ipa }} </span>
<span> {{ $record->nilai_ips }} </span>
<span> {{ $record->nilai_matematika }} </span>
<span> {{ $record->nilai_indonesia }} </span>
<span> {{ $record->nilai_inggris }} </span>
<span> {{ $record->nilai_arab }} </span>
<span> {{ $record->bobot_nilai_akademik }} </span>
<span> {{ $record->bobot_nilai_praktik }} </span>
<span> {{ $record->nilai_akademik }} </span>
<span> {{ $record->nilai_praktik }} </span>
<span> {{ $record->status_pendaftaran }} </span>
<span> {{ $record->kelas_id }} </span>
<span> {{ $record->tes_sesi }} </span>
<span> {{ $record->tes_ruang }} </span>
<span> {{ $record->tes_akademik_mulai }} </span>
<span> {{ $record->tes_akademik_selesai }} </span>
<span> {{ $record->tes_praktik_mulai }} </span>
<span> {{ $record->tes_praktik_selesai }} </span>
